# Generated by Django 3.2.8 on 2021-10-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sciName', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
            ],
        ),
    ]
